### PR TITLE
Better sidebar menu

### LINKED ISSUE #114: Sidebar filter order
Presumably, Inbox, Archive, and Starred are the most important filters. We should move these to the top.

octobox

### PR DESCRIPTION
**Pull request by briannelson**
octobox

Closes #114

### CODE REVIEW

**Comment by briannelson** [comment]
octobox

**Comment by andrew** [comment]
@briannelson is this ready for merging? Looking good 👍

**Comment by briannelson** [comment]
Yup!

**Comment by andrew** [comment]
🚢

**Comment by andrew** [comment]
ooo new emoji 🤖

**Pull request merged**
