### PR TITLE
remember state of navigation cursor + js -> coffee + refactor

### LINKED ISSUE #70: Cursor position resets after archiving
If I leave several notifications to look at later and want to archive a bunch of ones below them, this means I have to scroll down past them every time. This feels inefficient to me!

### PR DESCRIPTION
**Pull request by karpiu**
Refactored navigation js code. Switched to coffeeScript and separated logic of navigation to a separate class. Fixes #70

### CODE REVIEW

**Comment by andrew** [comment]
That is a nice refactor!

**Comment by karpiu** [comment]
@andrew merge, maybe? :shipit:

**Comment by andrew** [comment]
I'm in two minds about the coffeescript rewrite, I like coffeescript myself but it will definitely be a barrier to future contributions

**Comment by karpiu** [comment]
CoffeeScript is a standard in Rails for a long time now. Bottom line is: you want to be a serious Rails developer, you have to learn CoffeeScript. Also it is supposed to make writing js easier (syntax is more Ruby-like).

**Comment by andrew** [comment]
Waiting to hear what @tarebyte thinks

**Comment by tarebyte** [comment]
Personally, I really don't like CoffeeScript and have removed it from all of my Rails projects.

> Bottom line is: you want to be a Rails developer, you have to learn CoffeeScript.

I know it's _usually_ what Rails applications use, but I don't really don't agree that you have to know CoffeeScript to be a Rails developer. Rails the framework is not tied to a syntactically sugar coated version of JavaScript.

But like I said that's just my opinion.

Also for what it's worth, github.com the app doesn't use CoffeeScript anymore either. We moved away from it and started writing our JavaScript in ES6 standard with Babel.

**Comment by andrew** [comment]
Ok going to close this, @karpiu do you fancy trying to fix the bug with regular Js instead?

Should be said that I don't really want to add Babel/webpack either at this point 😬

**Comment by karpiu** [comment]
@andrew fixed the bug, but without refactor this time. Not sure how you want to structure your js code, but since nobody likes coffeescript here I am not touching this one.

**Pull request closed without merging**
