### PR TITLE
navigation cursor remembers its position

### LINKED ISSUE #70: Cursor position resets after archiving
If I leave several notifications to look at later and want to archive a bunch of ones below them, this means I have to scroll down past them every time. This feels inefficient to me!

### PR DESCRIPTION
**Pull request by karpiu**
fixes #70

### CODE REVIEW

**Comment by tarebyte** [comment]
@karpiu I'm seeing some weird jumping of the cursor that I don't think if quite right. What do you think?

jumpy

**Comment by karpiu** [comment]
@tarebyte I will check it tomorrow.

**Comment by karpiu** [comment]
@tarebyte the problem is that turbolinks is caching previously visited pages. I added a function that clears the cursor before page is cached. You still might experience a little flicker on a cursor but now it should be only in place. Is that acceptable?

**Comment by andrew** [comment]
🚢

**Pull request merged**
